version: '3'

services:
  web:
    build: .
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/media
      - bundle:/usr/local/bundle
    depends_on:
      - db
  db:
    image: mysql:8.0.15
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-confd:/etc/mysql/conf.d
volumes:
  bundle:
  mysql_data: