version: '3'

services:
  rails:
    build: .
    env_file:
      - env/rails.env
      - env/mysql.env
    command: > 
      bash -c "rm -f ./tmp/pids/* && 
      rails s"
    volumes:
      - .:/media
      - bundle:/usr/local/bundle
      - public-data:/media/public
      - tmp-data:/media/tmp
    depends_on:
      - db
  db:
    image: mysql:8.0.15
    env_file:
      - env/mysql.env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-confd:/etc/mysql/conf.d
  nginx:
    build:
      context: containers/nginx
    volumes:
      - public-data:/media/public
      - tmp-data:/media/tmp
      - ./containers/nginx/log:/var/log/nginx
      - ./cert:/etc/mkcert/mst-tokuse-portfolio.com
      - ./containers/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    depends_on:
      - rails
volumes:
  bundle:
  mysql_data:
  public-data:
  tmp-data: