version: '3'

services:
  rails:
    build: .
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: > 
      bash -c "rm -f ./tmp/pids/* && 
      rails s"
    volumes:
      - .:/media
      - bundle:/usr/local/bundle
      - public-data:/media/public
      - tmp-data:/media/tmp
    depends_on:
      - db
  db:
    image: mysql:8.0.15
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-confd:/etc/mysql/conf.d
  nginx:
    build:
      context: containers/nginx
    volumes:
      - public-data:/media/public
      - tmp-data:/media/tmp
      - ./containers/nginx/log:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - rails
volumes:
  bundle:
  mysql_data:
  public-data:
  tmp-data: