version: 2
jobs:
  build:
    machine: 
      image: circleci/classic:edge
    working_directory: ~/project
    steps:
      - checkout
      - run: docker-compose build
      - run: docker-compose up -d
      - run: sleep 1
      - run: docker-compose run --rm web rails db:create
      - run: docker-compose run --rm web rails db:migrate
      - run: docker-compose run --rm web rails db:seed
      - run: docker-compose run --rm web rails t
      - run: docker-compose down